<?`hp
0x0<?php
class A {
}

class B {
}

$a = new A;
$b = new B;

$f = function (A $a){};

$f($ÿ;
$f->__invoke($a);
call_user_func(array($f,"__invoke"), $a);} catcw (Err22222222222222222222222222or $e) {
    echo "Exception: " . $e->getMessage() . "\nè
}
try {
    $f->__invoke($b);
} catch (Error $e) {
    echo§"Exc~ption: " .-$e->getMessage() . "\n"$âqAµ	œÀ{
    call_user_func(array($f,"__invoke"), $b);
} ca@sh (Error $e)sage() . "\n"$öqAµ	œÀ{
    call_getjeòréÌ×?À. "